### ISSUE TITLE
Dropdown not working on Windows Phone

### ISSUE THREAD

**Issue by pensiero** [Formstone/Formstone#8] opened 2015-04-25 12:12 UTC
I tried with IE on Windows Phone 8.1 and clicking on a dropdown it doesn't do anything. While on Android everything is ok.

**Comment by pensiero** [comment] 2015-05-06 14:41
Any news about this? Can I help you in any way?

**Comment by benplum** [comment] 2015-05-08 14:15
I'll check this out shortly.

**Comment by pensiero** [comment] 2015-05-08 14:39
Thanks a lot :+1:

**Comment by benplum** [comment] 2015-05-08 15:53
I just tested on a Lumia running Windows 8.1 and can not reproduce the issue. All dropdowns open and update properly. Do you have any more info on the issues?

**Comment by Leen15** [comment] 2015-05-08 22:13
Hi, same problem here with a lumia 640xl wp 8.1 update 2.

In demo page (http://formstone.it/components/dropdown/) i can scroll and select items in multiple/expanded view, but closed dropdown doesn't work, none of them open view when tapped.

**Comment by mitch-tofi** [comment] 2015-12-14 00:49
Can reproduce this issue using window edge browser (windows 10) and using their device emulation, drop downs wont expand.

**Comment by benplum** [comment] 2015-12-14 22:13
Closed in 0.8.32.

**Closed as completed by benplum** 2015-12-14 22:13 UTC

**Comment by mitch-tofi** [comment] 2015-12-14 22:28
Hi i can confirm this now works, however just to verify, shouldn't it be showing the native drop down list not the stylized one to be consistent with other mobile devices? 

Disclaimer, im not using a windows phone device so i cant say with certainty that this is the case.

It appeared that when i was debugging prior to your fix the mousedown event wasnt propogating to the select box.

as an ultra dodgey work around, to hotfix the issue, i used javascript to detect whether the browser was **IEMobile** or **Windows Phone**, and the applied a css class to the html node.

once that was done, i changed the z-index of the **fs-dropdown-element**, to render over the button so the mouse event could propogate.

```
    <script>
        var ieMobile = navigator.userAgent.indexOf('IEMobile') !== -1 || navigator.userAgent.indexOf('Windows Phone') !== -1;
        if (ieMobile) {
            $("html").addClass("ie-mobile");
        }
    </script>
    <style>
        .ie-mobile .fs-dropdown-element {
            z-index: 33 !important;
        }
    </style>
```

**Comment by benplum** [comment] 2015-12-15 02:05
I think we both hit on the underlying issue, which is that the event is not firing on the standard select element. I like your solution, and it may make it into an upcoming release, I just want to weigh the options and test a few ideas. And to answer your first question, this is a bit of a cop out - I would rather have the default options overlay display, not the custom styled dropdown. 

Side rant: I really hate that the library contains any browser sniffing at all, but because of inconsistencies such as this one it's still a necessary evil for certain edge cases.

**Comment by mitch-tofi** [comment] 2015-12-15 03:38
Completely agree, A solution where we don't have to hack around and do browser detects, I just used it as a stop gap, to get something out the door. However your current solution at least for now gives other users something that works, and its appreciated that you turned it around so fast.
